### ISSUE TITLE
Пропадает, после выхода из мира.

### ISSUE THREAD

**Issue by weacomeout** [ElvUI-WotLK/ElvUI_DTBars2#1]
С последним обновлением ElvUI, ElvUI_Enhanced и ElvUI_AddOnSkins, полоса с информацией пропадает, если выйти из мира и зайти назад. 
Вот я удалил полосу, настроил заново, она в самом верху экрана, по центру:
![WoWScrnShot_040320_120333](https://user-images.githubusercontent.com/57728292/78344034-6e124980-75a4-11ea-89dd-d01340346342.jpg)
Вот я релогнулся. Полоса с информацией пропала:
![WoWScrnShot_040320_120348](https://user-images.githubusercontent.com/57728292/78344074-81bdb000-75a4-11ea-848d-7e95bafb9fcd.jpg)
Хотя, при показе фиксаторов, полоса DTB2 явно присутствует:
![WoWScrnShot_040320_121026](https://user-images.githubusercontent.com/57728292/78344489-217b3e00-75a5-11ea-984d-c4da8623d183.jpg)

**Comment by GodinRaider-zz** [comment]
Тоже самое и у меня.
Если зайти в настройки и поменять один из текстов на другой, то все тексты на панели появятся.
